### ISSUE TITLE
Sauerbrauten freezes in flatpak

### ISSUE THREAD

**Issue by wpfan1000** [flathub/org.sauerbraten.Sauerbraten#7]
Hi I installed Sauerbrauten and it freezes on startup, it also freezes Gnome shell.
I need to escape to command line and reboot my Linux.
I may have changed the settings for Sauerbrauten using Flatseal and so this may be my mistake.
But I do not know what the correct settings for Sauerbrauten would be. How would I be able to find this out?
Also, it may not be the settings in Flatseal - what else could I do to prevent Sauerbrauten from freezing?
Thanks ahead of time…

(I initially posted this on flathub and someone suggested I contact you.

**Comment by AsciiWolf** [comment]
Hmm, I just tried Sauerbraten on my Fedora 35 system with GNOME 41 (with Wayland session) and everything worked fine, no freeze. What is your hardware configuration and distro/GNOME version?

**Comment by wpfan1000** [comment]
Hi, thanks for your message.
MY hardware is an old Dell E6510 laptop.
I was running Fedora on this laptop for 2 years and Sauerbrauten ran fine on Fedora, so I dont think it is the hardware.
I switched to Rocky Linux 8.4, which is bit for bit compatible with RHEL 8, which as you likely know, is derived from Fedora.
Gnome shell is version 3.32.2
I am wondering if I changed some settings for Sauerbrauten in Flatseal. Unfortunately I do not know what the correct settings should be. Please let me know if you know of any required settings.....
Thanks again.....

**Comment by wpfan1000** [comment]
I did:
- A Reset of Sauerbrauten in Flatseal
- A reinstall of Sauerbrauten
- An OS update
And this fixed the issue.
Thanks though for your time and attention to my post.
